---
- name: Install passwordless sudo for user
  when: passwordless_sudo_uninstall == false
  block:
    - name: Install
      ansible.builtin.include_tasks: install.yml

- name: Uninstall passwordless sudo for user
  when: passwordless_sudo_uninstall == true
  block:
    - name: Uninstall
      ansible.builtin.include_tasks: uninstall.yml
