---
- name: Create sudoers file for user
  when: passwordless_sudo_user | length > 0
  become: true
  ansible.builtin.copy:
    content: "{{ passwordless_sudo_user }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ passwordless_sudo_user }}-user"
    mode: 0440
    force: true
    validate: /usr/sbin/visudo -cf %s
